version: 2
updates:
  - package-ecosystem: "github-actions"
    reviewers:
      - 'citizensadvice/devops'
      - 'MatthewCane'
    directory: "/"
    schedule:
      interval: "weekly"
      day: 'monday'
      time: '09:00'
