name: Test Workflow

on:
  - workflow_dispatch

env:
  TEST_CHANNEL: "C07AGEKN0CB" #matt-test-channel

jobs:
  test-success:
    name: Test Success
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: citizensadvice/message-slack-action@feat/add-short-message-option
        with:
          title: 'Testing Message'
          message: 'Testing the normal message'
          channel_id: ${{ env.TEST_CHANNEL }}
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test-success-short:
    name: Test Success Short
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: citizensadvice/message-slack-action@feat/add-short-message-option
        with:
          title: 'Short Testing Message'
          message: 'Testing the short message'
          channel_id: ${{ env.TEST_CHANNEL }}
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message_length: 'short'

  fail-1:
    name: Test Failure
    runs-on: ubuntu-latest
    needs: test-success
    steps:
      - name: Trigger failure
        run: exit 1

  fail-2:
    name: Test Failure
    runs-on: ubuntu-latest
    needs: test-success
    steps:
      - name: Trigger failure
        run: exit 1

  fail-short:
    name: Test Failure
    runs-on: ubuntu-latest
    needs: test-success-short
    steps:
      - name: Trigger failure
        run: exit 1

  test-failure:
    name: Test Failure
    runs-on: ubuntu-latest
    needs:
      - fail-1
      - fail-2
    if: always()
    steps:
      - name: Notify Slack
        uses: citizensadvice/message-slack-action@feat/add-short-message-option
        with:
          title: 'Testing Message'
          message: 'Testing the failure message'
          channel_id: ${{ env.TEST_CHANNEL }}
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test-failure-short:
    name: Test Failure Short
    runs-on: ubuntu-latest
    needs:
      - fail-short
    if: always()
    steps:
      - name: Notify Slack
        uses: citizensadvice/message-slack-action@feat/add-short-message-option
        with:
          title: 'Testing Message'
          message: 'Testing the short failure message'
          channel_id: ${{ env.TEST_CHANNEL }}
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}