name: Test Workflow

on:
  - workflow_dispatch

env:
  TEST_CHANNEL: "C07AGEKN0CB" #matt-test-channel

jobs:
  test-success:
    name: Test Success
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notify Slack
        uses: ./
        with:
          title: 'Testing Message'
          message: 'Testing the normal message'
          channel_id: ${{ env.TEST_CHANNEL }}
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test-success-compact:
    name: Test Success Compact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notify Slack
        uses: ./
        with:
          title: 'Compact Testing Message'
          message: 'Testing the compact message'
          channel_id: ${{ env.TEST_CHANNEL }}
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          compact: true

  fail-1:
    name: Test Failure 1
    runs-on: ubuntu-latest
    needs: test-success
    steps:
      - name: Trigger failure
        run: exit 1

  fail-2:
    name: Test Failure 2
    runs-on: ubuntu-latest
    needs: test-success
    steps:
      - name: Trigger failure
        run: exit 1

  test-failure:
    name: Test Failure Message
    runs-on: ubuntu-latest
    needs:
      - fail-1
      - fail-2
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Notify Slack
        uses: ./
        with:
          title: 'Testing Message'
          message: 'Testing the failure message'
          channel_id: ${{ env.TEST_CHANNEL }}
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test-failure-compact:
    name: Test Failure Message Compact
    runs-on: ubuntu-latest
    needs:
      - fail-1
      - fail-2
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Notify Slack
        uses: ./
        with:
          title: 'Testing Message'
          message: 'Testing the compact failure message'
          channel_id: ${{ env.TEST_CHANNEL }}
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          compact: true