name: Test Workflow

on: workflow_dispatch

env:
  TEST_CHANNEL: "C07AGEKN0CB"

jobs:
  test:
    name: Test Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: citizensadvice/message-slack-action@v1
        with:
          title: 'Testing Message'
          message: 'Testing the normal message'
          channel_id: ${{ env.TEST_CHANNEL }}
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Notify Slack
        uses: citizensadvice/message-slack-action@v1
        with:
          title: 'Testing Message'
          message: 'Testing the failure message'
          failure: 'true'
          channel_id: ${{ env.TEST_CHANNEL }}
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

